---
#- hosts: webservers
#  tasks:
#    - name: ensure apache is at the latest version
#      yum:
#        name: httpd
#        state: latest

- hosts: all
  become: yes
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: latest
    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: yes

